"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider as JotaiProvider } from "jotai";
import PagesHOC from "@/HOC/PagesHOC";
import { Suspense } from "react";
import { QueryClient, QueryClientProvider } from "react-query";
import { Toaster } from "@/components/ui/toaster";
import UserContextProvider from "@/HOC/UserContext";
import NextNProgress from "nextjs-progressbar";
//@ts-ignore
import { StripeProvider } from "react-stripe-elements";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--inter",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <Suspense fallback={<p>Loading...</p>}>
        {/* <StripeProvider apiKey={process.env.STRIPE_PK_TEST!}> */}
          <JotaiProvider>
            <QueryClientProvider client={queryClient}>
              <body
                id="app_wrapper"
                className={`${interFont.variable} relative`}
              >
                <UserContextProvider>
                <NextNProgress color="#FE7E00" />
                  <PagesHOC>
                    {children}
                    <Toaster />
                  </PagesHOC>
                </UserContextProvider>
              </body>
            </QueryClientProvider>
          </JotaiProvider>
        {/* </StripeProvider> */}
      </Suspense>
    </html>
  );
}
