"use client";
import { Toaster } from "@/components/ui/toaster";
import PagesHOC from "@/HOC/PagesHOC";
import { Inter } from "next/font/google";
import { QueryClient } from "react-query";
import "./globals.css";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--inter",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      {/* <Suspense fallback={<p>Loading...</p>}>
        <JotaiProvider>
          <QueryClientProvider client={queryClient}>
            <body id="app_wrapper" className={`${interFont.variable} relative`}>
              <UserContextProvider> */}
      <PagesHOC>
        {children}
        <Toaster />
      </PagesHOC>
      {/* </UserContextProvider>
            </body>
          </QueryClientProvider>
        </JotaiProvider>
      </Suspense> */}
    </html>
  );
}
