


export const LAST_FOOD_BOX_CONTINENNT ="LAST_FOOD_BOX_CONTINENNT";
export const LOCAL_CART_ITEMS ="LOCAL_CART_ITEMS";
export const CART_MODAL_OPEN ="CART_MODAL_OPEN";
export const MEALEXTRASELECTIONS ="MEALEXTRASELECTIONS";